"""add image_url column

Revision ID: 409f9fedaf0
Revises: ba402bc847b
Create Date: 2013-01-26 08:46:49.170068

"""

# revision identifiers, used by Alembic.
revision = '409f9fedaf0'
down_revision = 'ba402bc847b'

from alembic import op
import sqlalchemy as sa
import db
from db import Twitter
import json


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('image_url', sa.String(), nullable=True))
    ### end Alembic commands ###
    tt = Twitter.query.all()
    for t in tt:
        if not t.raw: continue

        raw = json.loads(t.raw)
        if 'profile_image_url' in raw:
            t.account.image_url = raw['profile_image_url']


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'image_url')
    ### end Alembic commands ###
