"""add modified column to question

Revision ID: ba402bc847b
Revises: None
Create Date: 2013-01-25 23:25:23.380413

"""

# revision identifiers, used by Alembic.
revision = 'ba402bc847b'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))
import db
from db import Question, Answer, Vote


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


    qq = Question.query.enable_eagerloads(False).add_column(sa.func.max(Vote.timestamp).label('max')).outerjoin(Answer).outerjoin(Vote).group_by(Question.id)
    for q, m in qq:
        if m is None:
            q.modified = q.added
        else:
            q.modified = m




def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'modified')
    ### end Alembic commands ###
